### ISSUE TITLE
Deliverable qol improvements

### ISSUE THREAD

**Issue by mempirate** [chainbound/valtrack#17]
```[tasklist]
## Tasks
- [x] Update README on how to run it (and a quick overview of how it works)
- [x] Do not require NATS, stdout can also print events
- [x] Config through CLI app (https://github.com/urfave/cli, docs: https://github.com/urfave/cli/blob/main/docs/v2/getting-started.md)
- [x] Re-use Prysms `params.MainnetConfig()` more
```

**Comment by namn-grg** [comment]
Fixed by #22 #23
