### ISSUE TITLE
Tracking: v0.0.2

### ISSUE THREAD

**Issue by mempirate** [chainbound/valtrack#24]
```[tasklist]
- [x] Get rid of Prysm fork
- [x] Clickhouse sink for events
- [x] Stateful consumer DB for tracking validators, derived from events
- [ ] https://github.com/chainbound/valtrack/issues/28
- [x] Configurable consumer name
```
