### ISSUE TITLE
NATS JetStream client

### ISSUE THREAD

**Issue by mempirate** [chainbound/valtrack#4]
## Context
To send events to our stateful collector, we'll use a persistent message queue called NATS. The first step is implementing a NATS JetStream client inside of the crawler that we can send events to. To test this locally I propose to use docker-compose with a NATS server image and a couple of crawlers.

```[tasklist]
## Tasks
- [ ] Docker-compose local test setup
- [x] Event serialization format (JSON or Protobuf)
- [x] Creation (or existence check) of the correct streams
- [x] Creation (or existence check) of the correct subjects or topics
- [x] Methods for sending events to NATS
```

Read more about NATS:
- https://docs.nats.io/nats-concepts/overview
- https://docs.nats.io/nats-concepts/jetstream
